import React, { useState } from "react";
import katex from "katex";
import { Check, Copy, Terminal, ExternalLink } from "lucide-react";

interface MarkdownRendererProps {
  content: string;
  className?: string;
}

// Escape HTML special characters for fallback display
const escapeHtml = (str: string): string =>
  str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

// Strip emojis and decorative symbols for a strictly minimal, clean look
export const stripEmojis = (text: string): string => {
  if (!text) return "";
  return text
    .replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{2300}-\u{23FF}\u{2B50}\u{2B55}\u{FE0F}\u{200D}]/gu, "")
    .replace(/[ \t]{2,}/g, " ");
};

// Sanitize LaTeX strings generated by LLMs to fix common syntax issues
export const cleanLatex = (math: string): string => {
  if (!math) return "";
  let s = math.trim();

  // Strip wrapping delimiters if still present inside
  if (s.startsWith("$$") && s.endsWith("$$") && s.length >= 4) {
    s = s.slice(2, -2).trim();
  } else if (s.startsWith("\\[") && s.endsWith("\\]") && s.length >= 4) {
    s = s.slice(2, -2).trim();
  } else if (s.startsWith("\\(") && s.endsWith("\\)") && s.length >= 4) {
    s = s.slice(2, -2).trim();
  } else if (s.startsWith("$") && s.endsWith("$") && s.length >= 2) {
    s = s.slice(1, -1).trim();
  }

  // 1. Decode HTML entities that may have entered through markdown
  s = s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/&le;/g, "\\le ")
    .replace(/&ge;/g, "\\ge ")
    .replace(/&times;/g, "\\times ")
    .replace(/&middot;/g, "\\cdot ");

  // 2. Fix accidental double backslashes before common LaTeX commands (e.g. \\text -> \text)
  s = s.replace(/\\\\([a-zA-Z]+)/g, "\\$1");

  // 3. Fix double backslashes before escaped symbols: \\_ -> \_, \\% -> \%
  s = s.replace(/\\\\([_&%#{}$])/g, "\\$1");

  // 4. Fix unescaped percent signs (in LaTeX, % starts a comment and swallows the rest of the equation)
  s = s.replace(/(?<!\\)%/g, "\\%");

  // 5. Fix common LLM unbraced multi-character subscripts in metrics, e.g. T_prefill -> T_{\text{prefill}}
  s = s.replace(/_([a-zA-Z0-9]{2,})(?![a-zA-Z0-9}])/g, "_{\\text{$1}}");

  return s;
};

// Render KaTeX inline math safely with error boundary fallback
export const renderKatexInline = (math: string): string => {
  const cleaned = cleanLatex(math);
  if (!cleaned) return "";
  try {
    return katex.renderToString(cleaned, {
      displayMode: false,
      throwOnError: true,
    });
  } catch {
    try {
      return katex.renderToString(cleaned, {
        displayMode: false,
        throwOnError: false,
      });
    } catch {
      return `<code class="px-1.5 py-0.5 rounded font-mono text-[11px] bg-[var(--brand-primary-light)] text-[var(--brand-primary)] font-semibold">${escapeHtml(cleaned)}</code>`;
    }
  }
};

// Render KaTeX block math safely with error boundary fallback
export const renderKatexBlock = (math: string): string => {
  const cleaned = cleanLatex(math);
  if (!cleaned) return "";
  try {
    return katex.renderToString(cleaned, {
      displayMode: true,
      throwOnError: true,
    });
  } catch {
    try {
      return katex.renderToString(cleaned, {
        displayMode: true,
        throwOnError: false,
      });
    } catch {
      return `<pre class="my-2 p-2.5 rounded-xl bg-[var(--bg-surface-subtle)]/70 dark:bg-[var(--bg-surface-subtle)] font-mono text-xs text-center text-[var(--brand-primary)] overflow-x-auto whitespace-pre-wrap">${escapeHtml(cleaned)}</pre>`;
    }
  }
};

// Helper component for rendered code blocks with copy functionality
const CodeBlock: React.FC<{ code: string; language?: string }> = ({ code, language }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="my-2.5 rounded-xl border border-[var(--border-medium)] bg-[var(--bg-surface-subtle)] dark:bg-[var(--bg-app)] text-[var(--text-main)] overflow-hidden text-xs shadow-xs">
      <div className="flex items-center justify-between px-3 py-1.5 bg-[var(--bg-surface-elevated)] dark:bg-[var(--bg-surface)] border-b border-[var(--border-subtle)] text-[10px] text-[var(--text-main)]/60 dark:text-[var(--text-muted)]">
        <div className="flex items-center gap-1.5">
          <Terminal className="h-3 w-3 text-[var(--brand-primary)]" />
          <span className="font-mono uppercase">{language || "text"}</span>
        </div>
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-1 hover:text-white transition-colors cursor-pointer"
        >
          {copied ? (
            <>
              <Check className="h-3 w-3 text-emerald-400" />
              <span className="text-emerald-400">Copied</span>
            </>
          ) : (
            <>
              <Copy className="h-3 w-3" />
              <span>Copy</span>
            </>
          )}
        </button>
      </div>
      <pre className="p-3 font-mono text-[11px] overflow-x-auto leading-relaxed text-[var(--text-main)]/90 dark:text-[var(--text-subheading)] whitespace-pre">
        {code}
      </pre>
    </div>
  );
};

// Tokenizer regex for inline elements: math ($$...$$, \[...\], \(...\), $...$), bold, inline code, links, italics
const INLINE_REGEX = /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\)|\$(?!\s)(?:[^$\\\n]|\\.)+?(?<!\s)\$|\*\*[^*]+?\*\*|`[^`]+?`|\[(?:[^\]]+?)\]\((?:[^)]+?)\)|\*[^*]+?\*|_[^_]+?_)/g;

// Helper for rendering inline text formatting (bold, italic, code, math, links)
export const renderInlineFormatting = (text: string): React.ReactNode[] => {
  const parts = text.split(INLINE_REGEX);

  return parts.map((part, idx) => {
    if (!part) return null;

    // Display math $$...$$
    if (part.startsWith("$$") && part.endsWith("$$") && part.length >= 4) {
      const math = part.slice(2, -2);
      const html = renderKatexBlock(math);
      return (
        <span
          key={idx}
          className="block my-1.5 text-center overflow-x-auto"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
    }

    // Display math \[...\]
    if (part.startsWith("\\[") && part.endsWith("\\]") && part.length >= 4) {
      const math = part.slice(2, -2);
      const html = renderKatexBlock(math);
      return (
        <span
          key={idx}
          className="block my-1.5 text-center overflow-x-auto"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
    }

    // Inline math \(...\)
    if (part.startsWith("\\(") && part.endsWith("\\)") && part.length >= 4) {
      const math = part.slice(2, -2);
      const html = renderKatexInline(math);
      return (
        <span
          key={idx}
          className="inline-flex items-center mx-0.5"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
    }

    // Inline math $...$
    if (part.startsWith("$") && part.endsWith("$") && part.length >= 2) {
      const inner = part.slice(1, -1);
      // Guard against false positive currency matches like $50 or $0.50
      if (/^\d+(?:[.,]\d+)?(?:\s*(?:k|M|B|USD|tokens))?$/i.test(inner.trim())) {
        return <span key={idx}>{part}</span>;
      }
      const html = renderKatexInline(inner);
      return (
        <span
          key={idx}
          className="inline-flex items-center mx-0.5"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
    }

    // Bold **...**
    if (part.startsWith("**") && part.endsWith("**") && part.length >= 4) {
      const inner = part.slice(2, -2);
      return (
        <strong key={idx} className="font-bold text-[var(--text-main)]">
          {renderInlineFormatting(inner)}
        </strong>
      );
    }

    // Inline code `...`
    if (part.startsWith("`") && part.endsWith("`") && part.length >= 2) {
      const inner = part.slice(1, -1);
      return (
        <code
          key={idx}
          className="px-1.5 py-0.5 rounded-md font-mono text-[11px] bg-[var(--border-subtle)] dark:bg-[var(--bg-surface-subtle)]/10 text-[var(--brand-primary)] dark:text-[var(--brand-secondary)] font-semibold border border-[var(--border-subtle)]"
        >
          {inner}
        </code>
      );
    }

    // Markdown Links [text](url)
    const linkMatch = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    if (linkMatch) {
      const linkText = linkMatch[1];
      const linkUrl = linkMatch[2];
      return (
        <a
          key={idx}
          href={linkUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-0.5 text-[var(--brand-primary)] underline underline-offset-2 hover:opacity-80 transition-opacity"
        >
          <span>{linkText}</span>
          <ExternalLink className="h-2.5 w-2.5 inline opacity-70" />
        </a>
      );
    }

    // Italic *...* or _..._
    if (
      (part.startsWith("*") && part.endsWith("*") && !part.startsWith("**") && part.length >= 2) ||
      (part.startsWith("_") && part.endsWith("_") && !part.startsWith("__") && part.length >= 2)
    ) {
      const inner = part.slice(1, -1);
      return (
        <em key={idx} className="italic text-[var(--text-main)]/90 dark:text-white/90">
          {renderInlineFormatting(inner)}
        </em>
      );
    }

    return <span key={idx}>{part}</span>;
  });
};

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ content, className = "" }) => {
  if (!content) return null;

  // Clean all emojis across the entire markdown content for a sleek minimal presentation
  const cleanContent = stripEmojis(content);
  const lines = cleanContent.split("\n");
  const elements: React.ReactNode[] = [];

  let inCodeBlock = false;
  let codeBlockLanguage = "";
  let codeBlockContent: string[] = [];

  let inMathBlock = false;
  let mathBlockDelim: "code" | "$$" | "\\[" = "$$";
  let mathBlockContent: string[] = [];

  let inTable = false;
  let tableRows: string[][] = [];

  let inList = false;
  let listItems: React.ReactNode[] = [];

  const flushList = () => {
    if (inList && listItems.length > 0) {
      elements.push(
        <ul key={`list-${elements.length}`} className="my-2 space-y-1 pl-4 list-disc marker:text-[var(--brand-primary)]/70 dark:marker:text-[var(--brand-primary)]/70 text-xs leading-relaxed text-[var(--text-main)]/90 dark:text-neutral-200">
          {listItems.map((item, i) => (
            <li key={i}>
              {item}
            </li>
          ))}
        </ul>
      );
      listItems = [];
      inList = false;
    }
  };

  const flushTable = () => {
    if (inTable && tableRows.length > 0) {
      const headerRow = tableRows[0];
      const bodyRows = tableRows.slice(1);

      elements.push(
        <div key={`table-${elements.length}`} className="my-2.5 overflow-x-auto rounded-lg border border-neutral-200 dark:border-neutral-800 shadow-2xs">
          <table className="w-full text-xs text-left">
            <thead className="bg-neutral-50 dark:bg-neutral-900/60 text-neutral-600 dark:text-neutral-300 border-b border-neutral-200 dark:border-neutral-800 text-[11px]">
              <tr>
                {headerRow.map((cell, idx) => (
                  <th key={idx} className="px-3 py-1.5 font-semibold">
                    {renderInlineFormatting(cell.trim())}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-200/60 dark:divide-neutral-800/60 bg-[var(--bg-card)]">
              {bodyRows.map((row, rowIdx) => (
                <tr key={rowIdx} className="hover:bg-neutral-50/70 dark:hover:bg-neutral-900/40 transition-colors">
                  {row.map((cell, cellIdx) => (
                    <td key={cellIdx} className="px-3 py-1.5 text-[11.5px] text-neutral-800 dark:text-neutral-200">
                      {renderInlineFormatting(cell.trim())}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
      tableRows = [];
      inTable = false;
    }
  };

  const flushMathBlock = () => {
    if (inMathBlock && mathBlockContent.length > 0) {
      const math = mathBlockContent.join("\n");
      const html = renderKatexBlock(math);
      elements.push(
        <div
          key={`math-${elements.length}`}
          className="my-2.5 py-2.5 px-3 rounded-lg bg-neutral-50/70 dark:bg-neutral-900/40 border border-neutral-200/70 dark:border-neutral-800/80 overflow-x-auto text-center shadow-2xs"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
      mathBlockContent = [];
      inMathBlock = false;
    }
  };

  const flushCodeBlock = () => {
    if (inCodeBlock && codeBlockContent.length > 0) {
      elements.push(
        <CodeBlock
          key={`code-${elements.length}`}
          code={codeBlockContent.join("\n")}
          language={codeBlockLanguage}
        />
      );
      codeBlockContent = [];
      codeBlockLanguage = "";
      inCodeBlock = false;
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // 1. In Math Block (multi-line $$ ... $$, \[ ... \], or ```math/latex)
    if (inMathBlock) {
      if (mathBlockDelim === "code" && trimmed.startsWith("```")) {
        flushMathBlock();
        continue;
      }
      if (mathBlockDelim === "$$" && (trimmed === "$$" || trimmed.endsWith("$$"))) {
        const closingIdx = line.lastIndexOf("$$");
        const prefix = line.slice(0, closingIdx).trim();
        if (prefix && prefix !== "$$") {
          mathBlockContent.push(prefix);
        }
        flushMathBlock();
        continue;
      }
      if (mathBlockDelim === "\\[" && (trimmed === "\\]" || trimmed.endsWith("\\]"))) {
        const closingIdx = line.lastIndexOf("\\]");
        const prefix = line.slice(0, closingIdx).trim();
        if (prefix && prefix !== "\\]") {
          mathBlockContent.push(prefix);
        }
        flushMathBlock();
        continue;
      }
      mathBlockContent.push(line);
      continue;
    }

    // 2. In Code Block
    if (inCodeBlock) {
      if (trimmed.startsWith("```")) {
        flushCodeBlock();
      } else {
        codeBlockContent.push(line);
      }
      continue;
    }

    // 3. Fenced Code Block / Math Block Start
    if (trimmed.startsWith("```")) {
      flushList();
      flushTable();
      const lang = trimmed.slice(3).trim().toLowerCase();
      // Directly render math / latex / katex blocks as mathematical formulas
      if (lang === "math" || lang === "latex" || lang === "katex" || lang === "tex") {
        inMathBlock = true;
        mathBlockDelim = "code";
        mathBlockContent = [];
      } else {
        inCodeBlock = true;
        codeBlockLanguage = trimmed.slice(3).trim();
        codeBlockContent = [];
      }
      continue;
    }

    // 4. Single-Line Display Math $$...$$
    if (trimmed.startsWith("$$") && trimmed.endsWith("$$") && trimmed.length >= 4) {
      flushList();
      flushTable();
      const math = trimmed.slice(2, -2);
      const html = renderKatexBlock(math);
      elements.push(
        <div
          key={`math-${elements.length}`}
          className="my-2.5 py-2.5 px-3 rounded-lg bg-neutral-50/70 dark:bg-neutral-900/40 border border-neutral-200/70 dark:border-neutral-800/80 overflow-x-auto text-center shadow-2xs"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
      continue;
    }

    // 5. Single-Line Display Math \[...\]
    if (trimmed.startsWith("\\[") && trimmed.endsWith("\\]") && trimmed.length >= 4) {
      flushList();
      flushTable();
      const math = trimmed.slice(2, -2);
      const html = renderKatexBlock(math);
      elements.push(
        <div
          key={`math-${elements.length}`}
          className="my-2.5 py-2.5 px-3 rounded-lg bg-neutral-50/70 dark:bg-neutral-900/40 border border-neutral-200/70 dark:border-neutral-800/80 overflow-x-auto text-center shadow-2xs"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
      continue;
    }

    // 6. Multi-Line Display Math Start $$
    if (trimmed.startsWith("$$")) {
      flushList();
      flushTable();
      inMathBlock = true;
      mathBlockDelim = "$$";
      mathBlockContent = [];
      const rest = trimmed.slice(2).trim();
      if (rest) {
        mathBlockContent.push(rest);
      }
      continue;
    }

    // 7. Multi-Line Display Math Start \[
    if (trimmed.startsWith("\\[")) {
      flushList();
      flushTable();
      inMathBlock = true;
      mathBlockDelim = "\\[";
      mathBlockContent = [];
      const rest = trimmed.slice(2).trim();
      if (rest) {
        mathBlockContent.push(rest);
      }
      continue;
    }

    // 8. Markdown Table lines
    if (trimmed.startsWith("|") && trimmed.endsWith("|")) {
      flushList();
      // Skip separator row like |---|---|
      if (/^\|[-:\s|]+\|$/.test(trimmed)) {
        continue;
      }
      const cells = trimmed
        .slice(1, -1)
        .split("|")
        .map((c) => c.trim());
      inTable = true;
      tableRows.push(cells);
      continue;
    } else {
      flushTable();
    }

    // 9. Headings
    if (trimmed.startsWith("### ")) {
      flushList();
      elements.push(
        <h4
          key={`h4-${elements.length}`}
          className="text-[11px] font-semibold tracking-wider uppercase text-[var(--brand-primary)] pt-3 pb-1 border-b border-neutral-200/50 dark:border-neutral-800/60 flex items-center gap-1.5"
        >
          {renderInlineFormatting(trimmed.slice(4))}
        </h4>
      );
      continue;
    }

    if (trimmed.startsWith("## ")) {
      flushList();
      elements.push(
        <h3
          key={`h3-${elements.length}`}
          className="text-xs font-semibold text-[var(--text-main)] dark:text-neutral-100 pt-3.5 pb-1 border-b border-neutral-200/40 dark:border-neutral-800/50"
        >
          {renderInlineFormatting(trimmed.slice(3))}
        </h3>
      );
      continue;
    }

    if (trimmed.startsWith("# ")) {
      flushList();
      elements.push(
        <h2
          key={`h2-${elements.length}`}
          className="text-sm font-bold text-[var(--text-main)] pt-4 pb-1.5"
        >
          {renderInlineFormatting(trimmed.slice(2))}
        </h2>
      );
      continue;
    }

    // 10. Bullet Lists (- or * or •)
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ") || trimmed.startsWith("• ")) {
      inList = true;
      const itemContent = trimmed.replace(/^[-*•]\s+/, "");
      listItems.push(renderInlineFormatting(itemContent));
      continue;
    }

    // 11. Numbered Lists (1. 2. 3.)
    if (/^\d+\.\s+/.test(trimmed)) {
      inList = true;
      const itemContent = trimmed.replace(/^\d+\.\s+/, "");
      listItems.push(renderInlineFormatting(itemContent));
      continue;
    }

    // 12. Blockquote (> ...)
    if (trimmed.startsWith("> ")) {
      flushList();
      const quoteText = trimmed.slice(2);
      elements.push(
        <div
          key={`quote-${elements.length}`}
          className="my-2 pl-3 py-1 border-l-2 border-[var(--brand-primary)] text-xs text-neutral-600 dark:text-neutral-300 italic bg-neutral-50/60 dark:bg-neutral-900/30 rounded-r-md"
        >
          {renderInlineFormatting(quoteText)}
        </div>
      );
      continue;
    }

    // 13. Empty line / Spacing
    if (trimmed === "") {
      flushList();
      continue;
    }

    // 14. Standard Paragraph
    flushList();
    elements.push(
      <p key={`p-${elements.length}`} className="my-1 text-xs text-[var(--text-main)]/90 dark:text-neutral-200/90 leading-relaxed font-sans">
        {renderInlineFormatting(trimmed)}
      </p>
    );
  }

  // Final flush for unclosed structures at EOF (e.g. streaming or truncated output)
  flushList();
  flushTable();
  flushMathBlock();
  flushCodeBlock();

  return <div className={`space-y-1 ${className}`}>{elements}</div>;
};
