import csv
import gzip
import io
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from app.models.db.models import BenchmarkRun


class ReportExporter:
    """Multi-format export engine for LLMark benchmark reports."""

    @classmethod
    def generate_markdown(cls, run: BenchmarkRun) -> str:
        """Generate a GitHub Flavored Markdown summary report."""
        goodput = run.goodput_pct if run.goodput_pct is not None else 0.0
        tps_decode = run.tps_decode if run.tps_decode is not None else 0.0
        completed = run.completed_requests if run.completed_requests is not None else 0
        failed = run.failed_requests if run.failed_requests is not None else 0
        cost = run.total_cost_usd if run.total_cost_usd is not None else 0.0
        duration = run.duration_seconds if run.duration_seconds is not None else 1
        req_rate = completed / max(1, duration)

        ttft_p50 = run.ttft_p50 if run.ttft_p50 is not None else 0.0
        ttft_p75 = run.ttft_p75 if run.ttft_p75 is not None else 0.0
        ttft_p95 = run.ttft_p95 if run.ttft_p95 is not None else 0.0
        ttft_p99 = run.ttft_p99 if run.ttft_p99 is not None else 0.0

        itl_p50 = run.itl_p50 if run.itl_p50 is not None else 0.0
        itl_p75 = run.itl_p75 if run.itl_p75 is not None else 0.0
        itl_p95 = run.itl_p95 if run.itl_p95 is not None else 0.0
        itl_p99 = run.itl_p99 if run.itl_p99 is not None else 0.0
        max_itl = run.max_itl if run.max_itl is not None else 0.0

        dns_p50 = run.dns_p50 if run.dns_p50 is not None else 0.0
        tcp_p50 = run.tcp_p50 if run.tcp_p50 is not None else 0.0
        tls_p50 = run.tls_p50 if run.tls_p50 is not None else 0.0

        md = f"""# ⚡ LLMark Benchmark Report: {run.name or 'Benchmark Run'}

**Model:** `{run.model}` | **Vendor:** `{run.vendor}` | **Run ID:** `{run.id}`  
**Workload:** `{run.workload_preset}` | **Concurrency:** `{run.concurrency}` streams | **Duration:** `{run.duration_seconds}s`  
**Status:** `{run.status}` | **Timestamp:** `{run.created_at.isoformat() if run.created_at else 'N/A'}`

---

## 📊 Summary Performance Metrics

| Metric | Measured Value | Unit / Evaluation |
|---|---|---|
| **Goodput (SLO Yield)** | **{goodput:.1f}%** | Target Satisfied |
| **Decode Throughput** | **{tps_decode:.1f}** | tokens/sec |
| **Request Throughput** | **{req_rate:.1f}** | reqs/sec |
| **Total Requests** | **{completed}** completed / {failed} failed | Total: {run.total_requests or (completed + failed)} |
| **Total Cost** | **${cost:.4f}** | USD |

---

## ⏱️ Tail Latency Percentiles

| Percentile | Time to First Token (TTFT) | Inter-Token Latency (ITL) |
|---|---|---|
| **P50 (Median)** | {ttft_p50:.1f} ms | {itl_p50:.1f} ms |
| **P75** | {ttft_p75:.1f} ms | {itl_p75:.1f} ms |
| **P95** | {ttft_p95:.1f} ms | {itl_p95:.1f} ms |
| **P99** | {ttft_p99:.1f} ms | {itl_p99:.1f} ms |
| **Max ITL (Worst Freeze)** | — | **{max_itl:.1f} ms** |

---

## 🌐 Network Connection Waterfall Baseline

- **DNS Lookup:** `{dns_p50:.1f} ms`
- **TCP Handshake:** `{tcp_p50:.1f} ms`
- **TLS Handshake:** `{tls_p50:.1f} ms`

*Generated by LLMark — Microsecond Telemetry Standard for LLM Inference.*
"""
        return md

    @classmethod
    def generate_csv(cls, run: BenchmarkRun) -> str:
        """Generate an RFC 4180 CSV export of benchmark metrics."""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow(["Metric Category", "Metric Name", "Value", "Unit"])
        writer.writerow(["Run Info", "Run ID", run.id or "", "string"])
        writer.writerow(["Run Info", "Run Name", run.name or "", "string"])
        writer.writerow(["Run Info", "Vendor", run.vendor or "", "string"])
        writer.writerow(["Run Info", "Model", run.model or "", "string"])
        writer.writerow(["Run Info", "Workload Preset", run.workload_preset or "", "string"])
        writer.writerow(["Run Info", "Concurrency", run.concurrency or 1, "streams"])
        writer.writerow(["Run Info", "Duration", run.duration_seconds or 0, "seconds"])
        writer.writerow(["Summary", "Goodput", run.goodput_pct or 0.0, "%"])
        writer.writerow(["Summary", "TPS Decode", run.tps_decode or 0.0, "tok/s"])
        writer.writerow(["Summary", "Completed Requests", run.completed_requests or 0, "count"])
        writer.writerow(["Summary", "Failed Requests", run.failed_requests or 0, "count"])
        writer.writerow(["Summary", "Total Cost", run.total_cost_usd or 0.0, "USD"])
        writer.writerow(["Latency", "TTFT P50", run.ttft_p50 or 0.0, "ms"])
        writer.writerow(["Latency", "TTFT P75", run.ttft_p75 or 0.0, "ms"])
        writer.writerow(["Latency", "TTFT P95", run.ttft_p95 or 0.0, "ms"])
        writer.writerow(["Latency", "TTFT P99", run.ttft_p99 or 0.0, "ms"])
        writer.writerow(["Latency", "ITL P50", run.itl_p50 or 0.0, "ms"])
        writer.writerow(["Latency", "ITL P75", run.itl_p75 or 0.0, "ms"])
        writer.writerow(["Latency", "ITL P95", run.itl_p95 or 0.0, "ms"])
        writer.writerow(["Latency", "ITL P99", run.itl_p99 or 0.0, "ms"])
        writer.writerow(["Latency", "Max ITL", run.max_itl or 0.0, "ms"])
        writer.writerow(["Network", "DNS", run.dns_p50 or 0.0, "ms"])
        writer.writerow(["Network", "TCP", run.tcp_p50 or 0.0, "ms"])
        writer.writerow(["Network", "TLS", run.tls_p50 or 0.0, "ms"])

        return output.getvalue()

    @classmethod
    def generate_bundle(cls, run: BenchmarkRun) -> bytes:
        """Generate a compressed .llmark JSON bundle containing full run telemetry."""
        bundle_data = {
            "version": "1.0.0",
            "benchmark_id": run.id,
            "name": run.name,
            "vendor": run.vendor,
            "model": run.model,
            "workload_preset": run.workload_preset,
            "load_curve": run.load_curve,
            "concurrency": run.concurrency,
            "duration_seconds": run.duration_seconds,
            "status": run.status,
            "summary": {
                "goodput_pct": run.goodput_pct,
                "tps_decode": run.tps_decode,
                "total_requests": run.total_requests,
                "completed_requests": run.completed_requests,
                "failed_requests": run.failed_requests,
                "total_cost_usd": run.total_cost_usd,
            },
            "percentiles": {
                "ttft_p50": run.ttft_p50,
                "ttft_p75": run.ttft_p75,
                "ttft_p95": run.ttft_p95,
                "ttft_p99": run.ttft_p99,
                "itl_p50": run.itl_p50,
                "itl_p75": run.itl_p75,
                "itl_p95": run.itl_p95,
                "itl_p99": run.itl_p99,
                "max_itl": run.max_itl,
                "tpot_mean": run.tpot_mean,
            },
            "waterfall": {
                "dns_p50": run.dns_p50,
                "tcp_p50": run.tcp_p50,
                "tls_p50": run.tls_p50,
            },
            "config": run.config_snapshot,
            "created_at": run.created_at.isoformat() if run.created_at else None,
        }
        json_bytes = json.dumps(bundle_data, indent=2).encode("utf-8")
        return gzip.compress(json_bytes)

    @classmethod
    def generate_pdf(cls, run: BenchmarkRun) -> bytes:
        """Generate an executive PDF report using ReportLab with clean typography & palette styling."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []

        goodput = run.goodput_pct if run.goodput_pct is not None else 0.0
        tps_decode = run.tps_decode if run.tps_decode is not None else 0.0
        completed = run.completed_requests if run.completed_requests is not None else 0
        failed = run.failed_requests if run.failed_requests is not None else 0
        cost = run.total_cost_usd if run.total_cost_usd is not None else 0.0
        concurrency = run.concurrency if run.concurrency is not None else 1

        ttft_p50 = run.ttft_p50 if run.ttft_p50 is not None else 0.0
        ttft_p75 = run.ttft_p75 if run.ttft_p75 is not None else 0.0
        ttft_p95 = run.ttft_p95 if run.ttft_p95 is not None else 0.0
        ttft_p99 = run.ttft_p99 if run.ttft_p99 is not None else 0.0

        itl_p50 = run.itl_p50 if run.itl_p50 is not None else 0.0
        itl_p75 = run.itl_p75 if run.itl_p75 is not None else 0.0
        itl_p95 = run.itl_p95 if run.itl_p95 is not None else 0.0
        itl_p99 = run.itl_p99 if run.itl_p99 is not None else 0.0
        max_itl = run.max_itl if run.max_itl is not None else 0.0

        dns_p50 = run.dns_p50 if run.dns_p50 is not None else 0.0
        tcp_p50 = run.tcp_p50 if run.tcp_p50 is not None else 0.0
        tls_p50 = run.tls_p50 if run.tls_p50 is not None else 0.0

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#2C2C2C"),
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#612D53"),
        )
        section_style = ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading2"],
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#853953"),
            fontName="Helvetica-Bold",
            spaceBefore=14,
            spaceAfter=6,
        )

        # Header Title & Metadata
        story.append(Paragraph(f"LLMark Benchmark Report: {run.name or 'Run Summary'}", title_style))
        story.append(
            Paragraph(
                f"Model: <b>{run.model or 'Unknown'}</b> | Vendor: <b>{run.vendor or 'Unknown'}</b> | Workload: <b>{run.workload_preset or 'Standard'}</b> | Run ID: {run.id}",
                subtitle_style,
            )
        )
        story.append(Spacer(1, 12))

        # KPI Summary Table
        story.append(Paragraph("Executive Performance Summary", section_style))
        kpi_data = [
            ["Metric", "Value", "Metric", "Value"],
            ["Goodput (SLO Yield)", f"{goodput:.1f}%", "Decode TPS", f"{tps_decode:.1f} tok/s"],
            ["Completed Requests", f"{completed}", "Failed Requests", f"{failed}"],
            ["Total Cost (USD)", f"${cost:.4f}", "Concurrency", f"{concurrency} streams"],
        ]
        kpi_table = Table(kpi_data, colWidths=[140, 130, 140, 130])
        kpi_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F4")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#2C2C2C")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E4E4")),
                ]
            )
        )
        story.append(kpi_table)
        story.append(Spacer(1, 10))

        # Latency Percentiles Table
        story.append(Paragraph("Tail Latency Percentiles Breakdown", section_style))
        latency_data = [
            ["Percentile", "Time to First Token (TTFT)", "Inter-Token Latency (ITL)"],
            ["P50 (Median)", f"{ttft_p50:.1f} ms", f"{itl_p50:.1f} ms"],
            ["P75", f"{ttft_p75:.1f} ms", f"{itl_p75:.1f} ms"],
            ["P95", f"{ttft_p95:.1f} ms", f"{itl_p95:.1f} ms"],
            ["P99", f"{ttft_p99:.1f} ms", f"{itl_p99:.1f} ms"],
            ["Max ITL (Worst Freeze)", "—", f"{max_itl:.1f} ms"],
        ]
        latency_table = Table(latency_data, colWidths=[180, 180, 180])
        latency_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F4")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E4E4")),
                ]
            )
        )
        story.append(latency_table)
        story.append(Spacer(1, 10))

        # Network Waterfall Table
        story.append(Paragraph("Network Handshake Waterfall Baseline", section_style))
        waterfall_data = [
            ["Phase", "Measured Latency", "Description"],
            ["DNS Lookup", f"{dns_p50:.1f} ms", "Domain name resolution time"],
            ["TCP Connect", f"{tcp_p50:.1f} ms", "SYN/ACK connection handshake"],
            ["TLS Handshake", f"{tls_p50:.1f} ms", "Cryptographic key negotiation"],
        ]
        wf_table = Table(waterfall_data, colWidths=[140, 140, 260])
        wf_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F4")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E4E4")),
                ]
            )
        )
        story.append(wf_table)

        doc.build(story)
        return buffer.getvalue()
